#!/bin/bash

install() {
  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # prepare vars
  local name="buildx"
  # files
  local tmp_file="$name"
  local bin_file="$tmp_file"

  # prepare context
  cd $tmp_dir

  # reference: https://github.com/docker/buildx/releases
  # example:
  #   https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.darwin-arm64
  #   https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.darwin-amd64
  # generate url
  local url="https://github.com/docker/buildx/releases/download/$PACKAGE_CORE_VERSION/${name}-${PACKAGE_CORE_VERSION}.${platform}-${arch}"
  log::debug "[package][$name][$kernel][$arch] url: $url"

  # download
  os::download $tmp_file $url
  
  # make executable
  chmod +x $bin_file

  # install
  sudo mv $bin_file $usr_bin_dir/docker-buildx

  # clean
  rm -rf $tmp_dir

  # as docker plugin
  # https://github.com/docker/buildx
  mkdir -p ~/.docker/cli-plugins
  ln -sf $usr_bin_dir/docker-buildx ~/.docker/cli-plugins/docker-buildx
}

export -f install
